import {
  OmniversusBattleSchema,
  type OmniversusBattle,
} from "@/server/battle/domain/schema";
import { prepareBattleOutput } from "@/server/battle/pipeline/prepareBattleOutput";

type BattleFixtureOptions = {
  battleType?: "OBJECTIVE" | "SUBJECTIVE";
  confidenceScore?: number;
  winnerSide?: "A" | "B" | "DRAW" | "INCONCLUSIVE";
};

export function makeBattleFixture(
  options: BattleFixtureOptions = {},
): OmniversusBattle {
  const winnerSide = options.winnerSide ?? "A";
  const confidenceScore = options.confidenceScore ?? 82;
  const raw = {
    metadata: {
      battle_type: options.battleType ?? "OBJECTIVE",
      canon_scope: "COMIC_MAINLINE",
      assumptions: "Standard battle assumptions.",
    },
    rules: {
      assumption_set: "VSBW_SBA",
      location: "Central Park, New York City",
      starting_distance: "30 meters",
      prep_time: "none",
      prior_knowledge: "appearance only",
      equipment: "standard equipment",
      verse_equalization: "reasonable interaction only",
      rule_impact: "MINOR",
      rule_notes: "Standardized starting conditions.",
    },
    stat_model: {
      core_stats_used: ["AP", "DURABILITY", "SPEED"],
      numerical_stats_role: "SECONDARY",
      hax_is_not_numeric: true,
      stamina_policy: "Track stamina qualitatively.",
      notes: "No exact numerical model is required.",
    },
    fighters: [
      {
        side: "A",
        name: "Captain America",
        version: "Earth-616 standard gear",
        verse: "Marvel Comics",
        tier_rating: "Street tier",
        tier_basis: "Consistent street-level feats.",
        tier_claim_ids: ["C1"],
        profile_ap: "Peak human with shield-enhanced striking options.",
        profile_durability: "Peak human durability with shield mitigation.",
        profile_speed: "Peak human combat speed.",
        profile_stamina: "Exceptional stamina.",
        profile_abilities: "Tactics, shield use, hand-to-hand skill.",
        profile_resistances: "Strong pain tolerance.",
        profile_skill: "Elite combat training.",
        profile_weaknesses: ["Still human under lethal damage."],
        profile_win_conditions: ["Close range shield pressure."],
        profile_lose_conditions: ["Sustained ranged attrition."],
        profile_counters: ["Shield blocks gunfire lanes."],
        best_argument: "Superior shield defense and melee skill.",
        weakest_argument: "Can be pressured by sustained firearms.",
      },
      {
        side: "B",
        name: "Punisher",
        version: "Standard arsenal",
        verse: "Marvel Comics",
        tier_rating: "Street tier",
        tier_basis: "Consistent street-level feats.",
        tier_claim_ids: ["C2"],
        profile_ap: "Human weapons and explosives.",
        profile_durability: "Human durability with body armor.",
        profile_speed: "Trained human combat speed.",
        profile_stamina: "High stamina.",
        profile_abilities: "Firearms, ambush tactics, explosives.",
        profile_resistances: "High pain tolerance.",
        profile_skill: "Elite tactical experience.",
        profile_weaknesses: ["Less protected in close quarters."],
        profile_win_conditions: ["Keep distance and force attrition."],
        profile_lose_conditions: ["Gets forced into shield melee."],
        profile_counters: ["Explosives can redirect approach lanes."],
        best_argument: "Greater ranged lethality.",
        weakest_argument: "Less reliable answer once Captain closes.",
      },
    ],
    claims: [
      {
        id: "C1",
        side: "A",
        kind: "DIRECT_FEAT",
        tag: "DIRECT",
        category: "SKILL",
        text: "Captain America has elite close-quarters skill and shield defense.",
        source_ref: "Marvel Comics",
        source_type: "CANON",
        source_status: "VERIFIED",
        source_reliability: "PRIMARY",
        source_note: "Representative canon source.",
        evidence_level: "DIRECT",
        importance: "DECISIVE",
        confidence: 82,
        supports_verdict: winnerSide === "A",
        review_flag: "OK",
        contested: false,
        outlier: false,
        appeal_hint: "Verify exact issue references.",
      },
      {
        id: "C2",
        side: "B",
        kind: "DIRECT_FEAT",
        tag: "DIRECT",
        category: "RANGE",
        text: "Punisher has strong ranged pressure through firearms.",
        source_ref: "Marvel Comics",
        source_type: "CANON",
        source_status: "VERIFIED",
        source_reliability: "PRIMARY",
        source_note: "Representative canon source.",
        evidence_level: "DIRECT",
        importance: "HIGH",
        confidence: 78,
        supports_verdict: winnerSide === "B",
        review_flag: "OK",
        contested: false,
        outlier: false,
        appeal_hint: "Verify loadout assumptions.",
      },
    ],
    argument_chains: [
      {
        id: "CH1",
        side: "A",
        chain_type: "STAT_ADVANTAGE",
        title: "Shield approach converts range to melee.",
        conclusion: "Captain America can force decisive close exchanges.",
        premises: [
          {
            id: "P1.1",
            role: "FACT",
            claim_id: "C1",
            text: "Shield defense covers the approach.",
            contested: false,
          },
          {
            id: "P1.2",
            role: "FACT",
            claim_id: "C1",
            text: "Close combat favors Captain America.",
            contested: false,
          },
        ],
        inference_rule: "If ranged pressure is mitigated, melee skill decides.",
        inference: "Captain America has the more reliable route.",
        confidence: 78,
        contested: false,
        breaks_if: "Punisher keeps range indefinitely.",
        linked_claim_ids: ["C1"],
      },
      {
        id: "CH2",
        side: "B",
        chain_type: "ANTI_ARGUMENT",
        title: "Ranged pressure can punish approach.",
        conclusion: "Punisher has a real but less reliable win condition.",
        premises: [
          {
            id: "P2.1",
            role: "FACT",
            claim_id: "C2",
            text: "Firearms threaten from distance.",
            contested: false,
          },
          {
            id: "P2.2",
            role: "COUNTERPOINT",
            claim_id: "C1",
            text: "Shield defense reduces the most direct threat.",
            contested: false,
          },
        ],
        inference_rule: "Range matters only if distance can be maintained.",
        inference: "Punisher can win some exchanges but not the majority.",
        confidence: 66,
        contested: false,
        breaks_if: "Arena heavily favors ambush.",
        linked_claim_ids: ["C2"],
      },
    ],
    comparison: [
      {
        category: "SKILL",
        winner: "A",
        margin: "MEDIUM",
        reason: "Captain America is stronger in close combat.",
        claim_ids: ["C1"],
        contested: false,
      },
      {
        category: "RANGE",
        winner: "B",
        margin: "LARGE",
        reason: "Punisher has firearms and explosives.",
        claim_ids: ["C2"],
        contested: false,
      },
      {
        category: "WIN_CONDITION",
        winner: "A",
        margin: "SMALL",
        reason: "Captain's route is more repeatable.",
        claim_ids: ["C1", "C2"],
        contested: false,
      },
    ],
    ability_interactions: [
      {
        id: "AI1",
        attacker: "A",
        defender: "B",
        ability: "Shield pressure",
        ability_type: "DAMAGE",
        activation: "Manual",
        range: "Melee to short range",
        timing: "After closing distance",
        target_requirement: "Line of sight",
        defender_resistance: "Body armor only",
        resistance_basis: "Standard gear",
        structurally_similar_resistance: "None",
        deliverable: true,
        effective: "YES",
        relevance_to_win_condition: "Enables Captain's close-range finish.",
        reason: "Shield pressure is deliverable once range collapses.",
        counterplay: "Maintain distance.",
        contested: false,
        impact: "MAJOR",
        claim_ids: ["C1"],
        chain_ids: ["CH1"],
      },
    ],
    win_conditions: [
      {
        id: "WC1",
        side: "A",
        method: "Close range control and shield strikes.",
        type: "STAT_CHECK",
        requires: "Close distance.",
        blocked_by: "Sustained range control.",
        probability: "HIGH",
        claim_ids: ["C1"],
        chain_ids: ["CH1"],
        contested: false,
      },
      {
        id: "WC2",
        side: "B",
        method: "Ranged attrition.",
        type: "STAT_CHECK",
        requires: "Maintain distance.",
        blocked_by: "Shield approach.",
        probability: "MEDIUM",
        claim_ids: ["C2"],
        chain_ids: ["CH2"],
        contested: false,
      },
    ],
    quality_flags: {
      active_warnings: [],
      most_fragile_assumption: "Neutral terrain does not favor ambush.",
      confidence_cap_reason: "No confidence cap applied.",
    },
    narrative: [1, 2, 3, 4, 5].map((step) => ({
      step,
      title: `Exchange ${step}`,
      log: "The fighters trade pressure while Captain closes distance.",
      a_hp: 100 - step * 8,
      b_hp: 100 - step * 13,
      why: "Shield defense offsets ranged pressure over time.",
      claim_ids: ["C1", "C2"],
      chain_ids: ["CH1"],
      contested: false,
    })),
    verdict: {
      winner_side: winnerSide,
      winner_name: winnerSide === "A" ? "Captain America" : "Punisher",
      difficulty: "HIGH_DIFF",
      confidence_score: confidenceScore,
      data_confidence_score: 74,
      verdict_confidence_given_data_score: confidenceScore,
      verdict_confidence_robustness_score: 68,
      confidence_explanation: "The route is favored but not absolute.",
      primary_reason: "Shield defense makes Captain's close-range route reliable.",
      decisive_chain_id: "CH1",
      loser_best_argument: "Punisher's ranged pressure remains dangerous.",
      why_not_other_side: "Range is difficult to maintain consistently.",
      flip_condition: "Ambush terrain or heavier loadout.",
      key_factors: ["Shield defense", "Close-combat skill"],
      risk_factors: ["Loadout assumptions"],
      recommended_rematch: "Ambush map with prep time.",
      summary_3_sentences:
        "Captain America is favored in a neutral arena. Punisher has real ranged threat. The deciding factor is whether Captain can close safely.",
    },
  };

  const prepared = prepareBattleOutput(raw, {
    fighterA: "Captain America",
    fighterB: "Punisher",
    outputLanguage: "en",
    speedEqualized: false,
  });
  const parsed = OmniversusBattleSchema.safeParse(prepared);

  if (!parsed.success) {
    throw new Error(parsed.error.message);
  }

  return parsed.data;
}
