export const GeminiBattleOutputJsonSchema = {
  type: "object",
  properties: {
    metadata: {
      type: "object",
      properties: {
        title: { type: "string" },
        battle_type: { type: "string", enum: ["OBJECTIVE", "SUBJECTIVE"] },
        canon_scope: { type: "string" },
        speed_equalized: { type: "boolean" },
        assumptions: { type: "string" },
      },
      required: [
        "title",
        "battle_type",
        "canon_scope",
        "speed_equalized",
        "assumptions",
      ],
      propertyOrdering: [
        "title",
        "battle_type",
        "canon_scope",
        "speed_equalized",
        "assumptions",
      ],
    },
    rules: {
      type: "object",
      properties: {
        assumption_set: { type: "string", enum: ["VSBW_SBA", "CUSTOM"] },
        location: { type: "string" },
        starting_distance: { type: "string" },
        prep_time: { type: "string" },
        prior_knowledge: { type: "string" },
        equipment: { type: "string" },
        verse_equalization: { type: "string" },
        rule_impact: {
          type: "string",
          enum: ["NONE", "MINOR", "IMPORTANT", "MATCH_DECIDING"],
        },
        rule_notes: { type: "string" },
      },
      required: [
        "assumption_set",
        "location",
        "starting_distance",
        "prep_time",
        "prior_knowledge",
        "equipment",
        "verse_equalization",
        "rule_impact",
        "rule_notes",
      ],
      propertyOrdering: [
        "assumption_set",
        "location",
        "starting_distance",
        "prep_time",
        "prior_knowledge",
        "equipment",
        "verse_equalization",
        "rule_impact",
        "rule_notes",
      ],
    },
    stat_model: {
      type: "object",
      properties: {
        core_stats_used: {
          type: "array",
          items: {
            type: "string",
            enum: ["AP", "DURABILITY", "SPEED", "STAMINA"],
          },
        },
        numerical_stats_role: {
          type: "string",
          enum: ["NONE", "SECONDARY", "PRIMARY"],
        },
        hax_is_not_numeric: { type: "boolean" },
        stamina_policy: { type: "string" },
        notes: { type: "string" },
      },
      required: [
        "core_stats_used",
        "numerical_stats_role",
        "hax_is_not_numeric",
        "stamina_policy",
        "notes",
      ],
      propertyOrdering: [
        "core_stats_used",
        "numerical_stats_role",
        "hax_is_not_numeric",
        "stamina_policy",
        "notes",
      ],
    },
    fighters: {
      type: "array",
      items: {
        type: "object",
        properties: {
          side: { type: "string", enum: ["A", "B"] },
          name: { type: "string" },
          version: { type: "string" },
          verse: { type: "string" },
          tier_rating: { type: "string" },
          tier_basis: { type: "string" },
          tier_contested: { type: "boolean" },
          tier_claim_ids: {
            type: "array",
            items: { type: "string" },
          },
          source_note: { type: "string" },
          profile: {
            type: "object",
            properties: {
              ap: { type: "string" },
              speed: { type: "string" },
              durability: { type: "string" },
              stamina: { type: "string" },
              abilities: { type: "string" },
              resistances: { type: "string" },
              skill: { type: "string" },
              weaknesses: {
                type: "array",
                items: { type: "string" },
              },
              win_conditions: {
                type: "array",
                items: { type: "string" },
              },
              lose_conditions: {
                type: "array",
                items: { type: "string" },
              },
              counters: {
                type: "array",
                items: { type: "string" },
              },
            },
            required: [
              "ap",
              "speed",
              "durability",
              "stamina",
              "abilities",
              "resistances",
              "skill",
              "weaknesses",
              "win_conditions",
              "lose_conditions",
              "counters",
            ],
            propertyOrdering: [
              "ap",
              "speed",
              "durability",
              "stamina",
              "abilities",
              "resistances",
              "skill",
              "weaknesses",
              "win_conditions",
              "lose_conditions",
              "counters",
            ],
          },
          best_argument: { type: "string" },
          weakest_argument: { type: "string" },
        },
        required: [
          "side",
          "name",
          "version",
          "verse",
          "tier_rating",
          "tier_basis",
          "tier_contested",
          "tier_claim_ids",
          "source_note",
          "profile",
          "best_argument",
          "weakest_argument",
        ],
        propertyOrdering: [
          "side",
          "name",
          "version",
          "verse",
          "tier_rating",
          "tier_basis",
          "tier_contested",
          "tier_claim_ids",
          "source_note",
          "profile",
          "best_argument",
          "weakest_argument",
        ],
      },
    },
    claims: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          side: { type: "string", enum: ["A", "B", "BOTH", "SYSTEM"] },
          kind: {
            type: "string",
            enum: [
              "DIRECT_FEAT",
              "SCALING",
              "CALC",
              "STATEMENT",
              "INTERPRETATION",
              "ANTI_FEAT",
              "ABILITY",
              "RESISTANCE",
              "WEAKNESS",
              "SUBJECTIVE_REASON",
              "DATA_QUALITY",
            ],
          },
          tag: {
            type: "string",
            enum: [
              "DIRECT",
              "SCALING",
              "CALC",
              "STATEMENT",
              "INTERPRETATION",
              "ANTI_FEAT",
            ],
          },
          category: {
            type: "string",
            enum: [
              "AP",
              "DURABILITY",
              "SPEED",
              "RANGE",
              "STAMINA",
              "SKILL",
              "INTELLIGENCE",
              "ABILITY",
              "RESISTANCE",
              "WEAKNESS",
              "WIN_CONDITION",
              "CONSENSUS",
              "CULTURAL_WEIGHT",
              "DESIGN",
              "POPULARITY",
              "DATA_QUALITY",
            ],
          },
          text: { type: "string" },
          source_ref: { type: "string" },
          evidence_level: {
            type: "string",
            enum: [
              "DIRECT",
              "STRONG_SCALING",
              "WEAK_SCALING",
              "CALC_BASED",
              "STATEMENT_BASED",
              "INTERPRETATION",
              "CONSENSUS_ONLY",
              "UNKNOWN",
            ],
          },
          importance: {
            type: "string",
            enum: ["LOW", "MEDIUM", "HIGH", "DECISIVE"],
          },
          confidence: { type: "number" },
          contested: { type: "boolean" },
          outlier: { type: "boolean" },
          supports_verdict: { type: "boolean" },
          review_flag: {
            type: "string",
            enum: [
              "OK",
              "NEEDS_SOURCE",
              "POSSIBLE_OUTLIER",
              "BAD_SCALING_RISK",
              "CALC_DISPUTE",
              "MECHANICS_MISMATCH",
              "DATA_INPUT_RISK",
              "SUBJECTIVE_ONLY",
            ],
          },
          appeal_hint: { type: "string" },
        },
        required: [
          "id",
          "side",
          "kind",
          "tag",
          "category",
          "text",
          "source_ref",
          "evidence_level",
          "importance",
          "confidence",
          "contested",
          "outlier",
          "supports_verdict",
          "review_flag",
          "appeal_hint",
        ],
        propertyOrdering: [
          "id",
          "side",
          "kind",
          "tag",
          "category",
          "text",
          "source_ref",
          "evidence_level",
          "importance",
          "confidence",
          "contested",
          "outlier",
          "supports_verdict",
          "review_flag",
          "appeal_hint",
        ],
      },
    },
    argument_chains: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          side: { type: "string", enum: ["A", "B", "BOTH", "SYSTEM"] },
          chain_type: {
            type: "string",
            enum: [
              "STAT_ADVANTAGE",
              "ABILITY_INTERACTION",
              "RESISTANCE_CHECK",
              "WIN_CONDITION",
              "ANTI_ARGUMENT",
              "DATA_QUALITY",
              "SUBJECTIVE_REASONING",
            ],
          },
          title: { type: "string" },
          conclusion: { type: "string" },
          premises: {
            type: "array",
            items: {
              type: "object",
              properties: {
                id: { type: "string" },
                role: {
                  type: "string",
                  enum: [
                    "FACT",
                    "SCALING_LINK",
                    "RULE",
                    "ASSUMPTION",
                    "ABILITY_MECHANIC",
                    "RESISTANCE_CHECK",
                    "COUNTERPOINT",
                  ],
                },
                claim_id: { type: "string" },
                text: { type: "string" },
                contested: { type: "boolean" },
              },
              required: ["id", "role", "claim_id", "text", "contested"],
              propertyOrdering: ["id", "role", "claim_id", "text", "contested"],
            },
          },
          inference: { type: "string" },
          confidence: { type: "number" },
          breaks_if: { type: "string" },
          linked_claim_ids: {
            type: "array",
            items: { type: "string" },
          },
          contested: { type: "boolean" },
        },
        required: [
          "id",
          "side",
          "chain_type",
          "title",
          "conclusion",
          "premises",
          "inference",
          "confidence",
          "breaks_if",
          "linked_claim_ids",
          "contested",
        ],
        propertyOrdering: [
          "id",
          "side",
          "chain_type",
          "title",
          "conclusion",
          "premises",
          "inference",
          "confidence",
          "breaks_if",
          "linked_claim_ids",
          "contested",
        ],
      },
    },
    comparison: {
      type: "array",
      items: {
        type: "object",
        properties: {
          category: {
            type: "string",
            enum: [
              "AP",
              "DURABILITY",
              "SPEED",
              "RANGE",
              "STAMINA",
              "SKILL",
              "INTELLIGENCE",
              "ABILITY",
              "RESISTANCE",
              "WIN_CONDITION",
              "CONSENSUS",
              "CULTURAL_WEIGHT",
              "DESIGN",
              "POPULARITY",
            ],
          },
          winner: {
            type: "string",
            enum: ["A", "B", "TIE", "INCONCLUSIVE"],
          },
          margin: {
            type: "string",
            enum: ["NONE", "SMALL", "MEDIUM", "LARGE", "DECISIVE"],
          },
          reason: { type: "string" },
          claim_ids: {
            type: "array",
            items: { type: "string" },
          },
          contested: { type: "boolean" },
        },
        required: [
          "category",
          "winner",
          "margin",
          "reason",
          "claim_ids",
          "contested",
        ],
        propertyOrdering: [
          "category",
          "winner",
          "margin",
          "reason",
          "claim_ids",
          "contested",
        ],
      },
    },
    ability_interactions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          attacker: { type: "string", enum: ["A", "B"] },
          defender: { type: "string", enum: ["A", "B"] },
          ability: { type: "string" },
          ability_type: {
            type: "string",
            enum: [
              "DAMAGE",
              "DEFENSE",
              "BFR",
              "SEALING",
              "MIND",
              "SOUL",
              "DOMAIN",
              "CONTRACT",
              "CONCEPTUAL",
              "CAUSALITY",
              "TIME",
              "SPACE",
              "PASSIVE",
              "UTILITY",
              "OTHER",
            ],
          },
          activation: { type: "string" },
          range: { type: "string" },
          timing: { type: "string" },
          target_requirement: { type: "string" },
          defender_resistance: { type: "string" },
          resistance_basis: { type: "string" },
          structurally_similar_resistance: { type: "string" },
          deliverable: { type: "boolean" },
          effective: { type: "string", enum: ["YES", "NO", "UNCLEAR"] },
          impact: {
            type: "string",
            enum: ["NONE", "MINOR", "MAJOR", "WIN_CONDITION"],
          },
          reason: { type: "string" },
          relevance_to_win_condition: { type: "string" },
          counterplay: { type: "string" },
          contested: { type: "boolean" },
          claim_ids: {
            type: "array",
            items: { type: "string" },
          },
          chain_ids: {
            type: "array",
            items: { type: "string" },
          },
        },
        required: [
          "id",
          "attacker",
          "defender",
          "ability",
          "ability_type",
          "activation",
          "range",
          "timing",
          "target_requirement",
          "defender_resistance",
          "resistance_basis",
          "structurally_similar_resistance",
          "deliverable",
          "effective",
          "impact",
          "reason",
          "relevance_to_win_condition",
          "counterplay",
          "contested",
          "claim_ids",
          "chain_ids",
        ],
        propertyOrdering: [
          "id",
          "attacker",
          "defender",
          "ability",
          "ability_type",
          "activation",
          "range",
          "timing",
          "target_requirement",
          "defender_resistance",
          "resistance_basis",
          "structurally_similar_resistance",
          "deliverable",
          "effective",
          "impact",
          "reason",
          "relevance_to_win_condition",
          "counterplay",
          "contested",
          "claim_ids",
          "chain_ids",
        ],
      },
    },
    win_conditions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          side: { type: "string", enum: ["A", "B"] },
          method: { type: "string" },
          type: {
            type: "string",
            enum: [
              "STAT_CHECK",
              "ABILITY",
              "BFR",
              "INCAP",
              "KO",
              "DEATH",
              "STAMINA",
              "SKILL",
              "SUBJECTIVE_EDGE",
            ],
          },
          requires: { type: "string" },
          probability: {
            type: "string",
            enum: ["VERY_LOW", "LOW", "MEDIUM", "HIGH", "VERY_HIGH"],
          },
          blocked_by: { type: "string" },
          claim_ids: {
            type: "array",
            items: { type: "string" },
          },
          chain_ids: {
            type: "array",
            items: { type: "string" },
          },
          contested: { type: "boolean" },
        },
        required: [
          "id",
          "side",
          "method",
          "type",
          "requires",
          "probability",
          "blocked_by",
          "claim_ids",
          "chain_ids",
          "contested",
        ],
        propertyOrdering: [
          "id",
          "side",
          "method",
          "type",
          "requires",
          "probability",
          "blocked_by",
          "claim_ids",
          "chain_ids",
          "contested",
        ],
      },
    },
    quality_flags: {
      type: "object",
      properties: {
        active_warnings: {
          type: "array",
          items: { type: "string" },
        },
        most_fragile_assumption: { type: "string" },
        confidence_cap_reason: { type: "string" },
      },
      required: [
        "active_warnings",
        "most_fragile_assumption",
        "confidence_cap_reason",
      ],
      propertyOrdering: [
        "active_warnings",
        "most_fragile_assumption",
        "confidence_cap_reason",
      ],
    },
    audit: {
      type: "object",
      properties: {
        sources: { type: "string" },
        data_inputs: { type: "string" },
        canon: { type: "string" },
        tier_ap: { type: "string" },
        speed: { type: "string" },
        ability_interactions: { type: "string" },
        resistances: { type: "string" },
        logical_chains: { type: "string" },
        confidence: { type: "string" },
      },
      required: [
        "sources",
        "data_inputs",
        "canon",
        "tier_ap",
        "speed",
        "ability_interactions",
        "resistances",
        "logical_chains",
        "confidence",
      ],
      propertyOrdering: [
        "sources",
        "data_inputs",
        "canon",
        "tier_ap",
        "speed",
        "ability_interactions",
        "resistances",
        "logical_chains",
        "confidence",
      ],
    },
    narrative: {
      type: "array",
      items: {
        type: "object",
        properties: {
          step: { type: "number" },
          title: { type: "string" },
          log: { type: "string" },
          a_hp: { type: "number" },
          b_hp: { type: "number" },
          why: { type: "string" },
          claim_ids: {
            type: "array",
            items: { type: "string" },
          },
          chain_ids: {
            type: "array",
            items: { type: "string" },
          },
          contested: { type: "boolean" },
        },
        required: [
          "step",
          "title",
          "log",
          "a_hp",
          "b_hp",
          "why",
          "claim_ids",
          "chain_ids",
          "contested",
        ],
        propertyOrdering: [
          "step",
          "title",
          "log",
          "a_hp",
          "b_hp",
          "why",
          "claim_ids",
          "chain_ids",
          "contested",
        ],
      },
    },
    verdict: {
      type: "object",
      properties: {
        winner_side: {
          type: "string",
          enum: ["A", "B", "DRAW", "INCONCLUSIVE"],
        },
        winner_name: { type: "string" },
        difficulty: {
          type: "string",
          enum: [
            "NO_DIFF",
            "LOW_DIFF",
            "MID_DIFF",
            "HIGH_DIFF",
            "EXTREME_DIFF",
            "STOMP",
            "INCONCLUSIVE",
          ],
        },
        confidence_score: { type: "number" },
        data_confidence_score: { type: "number" },
        verdict_confidence_given_data_score: { type: "number" },
        verdict_confidence_robustness_score: { type: "number" },
        confidence_explanation: { type: "string" },
        primary_reason: { type: "string" },
        decisive_chain_id: { type: "string" },
        loser_best_argument: { type: "string" },
        why_not_other_side: { type: "string" },
        flip_condition: { type: "string" },
        key_factors: {
          type: "array",
          items: { type: "string" },
        },
        risk_factors: {
          type: "array",
          items: { type: "string" },
        },
        recommended_rematch: { type: "string" },
        summary_3_sentences: { type: "string" },
      },
      required: [
        "winner_side",
        "winner_name",
        "difficulty",
        "confidence_score",
        "data_confidence_score",
        "verdict_confidence_given_data_score",
        "verdict_confidence_robustness_score",
        "confidence_explanation",
        "primary_reason",
        "decisive_chain_id",
        "loser_best_argument",
        "why_not_other_side",
        "flip_condition",
        "key_factors",
        "risk_factors",
        "recommended_rematch",
        "summary_3_sentences",
      ],
      propertyOrdering: [
        "winner_side",
        "winner_name",
        "difficulty",
        "confidence_score",
        "data_confidence_score",
        "verdict_confidence_given_data_score",
        "verdict_confidence_robustness_score",
        "confidence_explanation",
        "primary_reason",
        "decisive_chain_id",
        "loser_best_argument",
        "why_not_other_side",
        "flip_condition",
        "key_factors",
        "risk_factors",
        "recommended_rematch",
        "summary_3_sentences",
      ],
    },
    appeals: {
      type: "array",
      items: {
        type: "object",
        properties: {
          reason: {
            type: "string",
            enum: [
              "WRONG_SOURCE",
              "WRONG_CANON_SCOPE",
              "OUTLIER",
              "BAD_SCALING",
              "CALC_DISPUTE",
              "MISTRANSLATION",
              "MECHANICS_MISMATCH",
              "MISSING_RESISTANCE",
              "DATA_INPUT_ERROR",
              "CHAIN_GAP",
              "SUBJECTIVE_CONSENSUS_DISPUTE",
              "CULTURAL_WEIGHT_DISPUTE",
              "OTHER",
            ],
          },
          target_ids: {
            type: "array",
            items: { type: "string" },
          },
          summary: { type: "string" },
          needed: { type: "string" },
        },
        required: ["reason", "target_ids", "summary", "needed"],
        propertyOrdering: ["reason", "target_ids", "summary", "needed"],
      },
    },
    ui: {
      type: "object",
      properties: {
        tags: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["tags"],
      propertyOrdering: ["tags"],
    },
  },
  required: [
    "metadata",
    "rules",
    "stat_model",
    "fighters",
    "claims",
    "argument_chains",
    "comparison",
    "ability_interactions",
    "win_conditions",
    "quality_flags",
    "audit",
    "narrative",
    "verdict",
    "appeals",
    "ui",
  ],
  propertyOrdering: [
    "metadata",
    "rules",
    "stat_model",
    "fighters",
    "claims",
    "argument_chains",
    "comparison",
    "ability_interactions",
    "win_conditions",
    "quality_flags",
    "audit",
    "narrative",
    "verdict",
    "appeals",
    "ui",
  ],
} as const;

export type GeminiBattleOutput = Record<string, unknown>;
