import type { DossierFactCategory } from "./types";

export const BASE_CRITICAL_DOSSIER_CATEGORIES: DossierFactCategory[] = [
  "VERSION",
  "AP",
  "PHYSICAL_STRENGTH",
  "DURABILITY",
  "SPEED",
  "STAMINA",
  "ABILITY",
  "RESISTANCE",
  "WEAKNESS",
  "WIN_CONDITION",
];

export const GROUP_CRITICAL_DOSSIER_CATEGORIES: DossierFactCategory[] = [
  "NUMBERS",
  "LOGISTICS",
  "COMMAND_STRUCTURE",
];

export const MAX_DOSSIER_FACTS = 56;

export const CAPABILITY_CATEGORY_MAP: Record<string, DossierFactCategory> = {
  ATTACK_POTENCY: "AP",
  PHYSICAL_STRENGTH: "PHYSICAL_STRENGTH",
  SPEED: "SPEED",
  DURABILITY: "DURABILITY",
  STAMINA: "STAMINA",
  RANGE: "RANGE",
  INTELLIGENCE: "INTELLIGENCE",
  SKILL: "SKILL",
  SENSES: "SENSES",
  STEALTH: "STEALTH",
  MOBILITY: "MOBILITY",
  ENDURANCE: "ENDURANCE",
  LOGISTICS: "LOGISTICS",
  COMMAND_STRUCTURE: "COMMAND_STRUCTURE",
  NUMBERS: "NUMBERS",
  TERRITORY_CONTROL: "TERRITORY_CONTROL",
  OTHER: "OTHER",
};
